### ISSUE TITLE
Problem Description and Value Proposition

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#24]
**Tasks**:
- [x] Describe the selected problem. @ddummann 
- [x] Detail the proposed solution. @ddummann 
- [x] Outline the revenue model. @eduardoh27 @Lina-go @ddummann 
- [x] Present the value proposition of the proposed solution. @marilynjov @mestradag @dcuevasa

**Comment by mestradag** [comment]
We presented at the begining of the Sprint 1 the problem, solution, revenue model and value proposition with the correctin of the feedback and analyzing the context.
