### ISSUE TITLE
Business Questions

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#29]
**Tasks:**
  - [x] 2 type 1 questions. - @ddummann 
  - [x] 4 type 2 questions. - @dcuevasa 
  - [x] 4 type 3 questions. - @Lina-go 
  - [x] 2 type 4 questions. - @marilynjov 
  - [x] 2 type 5 questions. - @mestradag
