### ISSUE TITLE
VD Map

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#30]
VD Map for your solution. The VD Map must display all *14* business questions, and the data sources used on it must be obtainable through the designed solution or are publicly available. This task will also be graded considering the quality of the provided business questions.

**Tasks:**

Add the new BQ:

- [x] Add the new type 1 question - @ddummann 
- [x] Add the new type 3 question - @Lina-go 
- [x] Add the new type 4 question - @marilynjov 
- [x] Add the new type 5 question - @mestradag 

Connecting the new BQ to the rest of the components:

- [x] Connect type 1 and type 5 BQ - @eduardoh27 
- [x] Connect type 3 and type 4 BQ - @dcuevasa

**Comment by dcuevasa** [comment]
The new BQs where added to the wiki and the VD Map
