### ISSUE TITLE
Viva Voce

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#33]
Record a Viva Voce justifying each part of the Sprint 1:

**Tasks:**
- [x] Justify design decisions and choices when defining the context for a solution focusing on business questions and the VD Map.
- [x] Justify design decisions and choices for personas, empathy maps, PAS, and context canvas.
- [x] Justify design decisions and choices for quality and functional scenarios.
- [x] Justify the use of design processes (DP) and artifacts to convert observations into solutions.
- [x] Prepare for evaluation in the Viva Voce.

**Comment by ddummann** [comment]
We'll do it better next time!
