### ISSUE TITLE
Ethics Video

### ISSUE THREAD

**Issue by ddummann** [ISIS3510-Team14/Wiki#34]
**Description:**
At the end of each sprint, each team should deliver (in the team WIKI) a video, no longer than 6 minutes, in which each member makes a reflection concerning the following:

1. The ethical implications of their work as part of the team.
2. The societal and environmental impact of the proposed product.
3. The ethical implications of the product.

This is a mandatory task, and the participation of all members of the team must be visible in the video.

**Tasks:**
- [ ] Create a video, no longer than 6 minutes, reflecting on the ethical implications of each member's work as part of the team.
- [ ] Reflect on the societal and environmental impact of the proposed product in the video.
- [ ] Discuss the ethical implications of the product in the video.
- [ ] Ensure all team members participate and are visible in the video.
- [ ] Upload the video to the team WIKI by the end of the sprint.

**Comment by ddummann** [comment]
Ethics video uploaded to youtube and putted on the wiki!
